[green_agent]
agentbeats_id = "019c1a6b-2cf4-7fc2-9a0d-c3aa3bbc9f22"
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}" }

[[participants]]
name = "web_agent_v3"
agentbeats_id = "019c1a6e-cc61-7141-a2bd-1b56c14bfac3"
env = { WEB_AGENT_TYPE = "google", GOOGLE_API_KEY = "${GOOGLE_API_KEY}", NEBIUS_API_KEY = "${NEBIUS_API_KEY}" }

[config]
task_description = "Go to Google and search for AgentBeats"
start_url = "https://www.google.com/"
max_steps = 3
num_tasks = 1
# Trigger CI run

